:silent call setwinvar(1, "&statusline", "original")
:silent call setwinvar(1, "&readonly", TRUE)
:silent call setwinvar(2, "&statusline", "merged_file")
:silent call setwinvar(3, "&statusline", "source")
:silent call setwinvar(3, "&readonly", TRUE)
