# source : https://wiki.archlinux.org/index.php/Color_Bash_Prompt

txtred='\[\033[0;31m\]' # Red
txtgrn='\[\033[0;32m\]' # Green
txtrst='\[\033[0m\]'    # Text Reset

PS1="\r\n________________________________________________ \d / \T (${txtgrn}\#${txtrst})\r\n${debian_chroot:+($debian_chroot)}\u@\h:${txtred}\w${txtrst}\r\n${txtgrn}>${txtrst} "

alias ls="ls --color=auto"

